In [41]:
import torch

In [42]:
batch_size = 10
features = 25
x = torch.rand((batch_size, features)) # 10 x 25

### Basic Indexing
**<code>x[i:j, k:p]</code>**

In [43]:
print(x[0,:].shape) # x[0]
print(x[:,0].shape)
print(x[2,:10].shape) # 3nd batch / 0~9 features

torch.Size([25])
torch.Size([10])
torch.Size([10])


### Fancy Indexing

**<code>x[indices]</code>**

In [44]:
x = torch.arange(10)
indices = [2,5,8]
print(x)
print(x[indices])

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([2, 5, 8])


**<code>x[row_list,col_list]</code>**

In [45]:
x = torch.rand((3,5))
print(x)

rows = torch.tensor([1,0])
cols = torch.tensor([4,0])

print(x[rows,cols]) # (1,4), (0,0) - matching
print(x[1,4], x[0,0])

tensor([[0.6947, 0.2745, 0.9988, 0.4585, 0.5665],
        [0.2874, 0.7599, 0.4569, 0.6647, 0.0226],
        [0.3382, 0.7435, 0.6131, 0.1507, 0.2063]])
tensor([0.0226, 0.6947])
tensor(0.0226) tensor(0.6947)


### More Advanced Indexing

**<code>x[conditions]</code>**

In [46]:
x = torch.arange(10)
print(x)

# conditioning
print(x[(x < 2) | (x > 8)])
print(x[(x < 2) & (x > 8)])
print(x[x.remainder(2) == 0]) # x[x%2==0]


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([0, 1, 9])
tensor([], dtype=torch.int64)
tensor([0, 2, 4, 6, 8])


<code>**torch.where**(**cond1**, satisfied->**f(x)**, unsatisfied->**g(x)**)</code>

In [47]:
print(torch.where(x>5, x, x*2)) # matching -> if x>5, stay x, if not, x*2

tensor([ 0,  2,  4,  6,  8, 10,  6,  7,  8,  9])


**<code>x.unique()</code>**

In [48]:
print(torch.tensor([0,0,1,2,2,3,4]).unique())

tensor([0, 1, 2, 3, 4])


**<code>x.ndimension()</code>**

In [49]:
z = torch.rand(5,5,5)
print(z.ndimension())

3


**<code>x.numel()</code>**

In [50]:
print(x.numel()) # num. of elements

10
