In [2]:
import torch

In [8]:
x = torch.tensor([1,2,3])
y = torch.tensor([9,8,7])
print(x)
print(y)

tensor([1, 2, 3])
tensor([9, 8, 7])


### Addition

<code>torch.add(x,y,out=?)</code>

In [9]:
z1 = torch.empty(3)
torch.add(x,y,out=z1)
print(z1)

tensor([10., 10., 10.])


<code>z = torch.add(x,y)</code>

In [10]:
z2 = torch.add(x,y)
print(z2)

tensor([10, 10, 10])


<code>z = x + y</code>

In [12]:
z = x + y
print(z)

tensor([10, 10, 10])


### Division

<code>torch.true_divide(x,y)</code>

In [13]:
z = torch.true_divide(x,y) # element-wise division if equal shape
print(z)

tensor([0.1111, 0.2500, 0.4286])


In [15]:
z = torch.true_divide(x,5) # broad-casting divison if divide by a single number
print(z)

tensor([0.2000, 0.4000, 0.6000])


### Inplace operations

<code>x.add_(y)</code>
<code>x.subtract_(y)</code>
<code>x.multiply_(y)</code>
<code>x.divide_(y)</code>

<code>_</code> means <code>inplace</code>

In [26]:
print("x:",x)

t1 = torch.ones(3)
t2 = torch.ones(3)
t3 = torch.ones(3)
t4 = torch.ones(3)

t1.add_(x) # _ means in-place
t2.subtract_(x)
t3.multiply_(5)
t4.divide_(10)

print(t1)
print(t2)
print(t3)
print(t4)

x: tensor([1, 2, 3])
tensor([2., 3., 4.])
tensor([ 0., -1., -2.])
tensor([5., 5., 5.])
tensor([0.1000, 0.1000, 0.1000])


### Exponentiation

<code>x.pow(2)</code>
<code>x ** 2</code>

In [29]:
z1 = x.pow(2) #1
z2 = x ** 2 #2
print(z1)
print(z2)

tensor([1, 4, 9])
tensor([1, 4, 9])


### Simple Comparison

In [31]:
z = x > 0 # element-wise comparision
print(z)

tensor([True, True, True])


### Matrix Multiplication

<code>M3 = torch.mm(M1, M2)</code>, <code>M3 = M1.mm(M2)</code>

In [34]:
x1 = torch.rand((2,5))
x2 = torch.rand((5,3))

M1 = torch.mm(x1, x2) #1
M2 = x1.mm(x2) #2
print(M1)
print(M2)

tensor([[1.7427, 1.3168, 1.3177],
        [2.4138, 1.7322, 2.1367]])
tensor([[1.7427, 1.3168, 1.3177],
        [2.4138, 1.7322, 2.1367]])


### Matrix exponentiation

<code>M2 = M.matrix_power(3)</code>
<code>M.mm(M).mm(M)</code>

In [144]:
M = torch.rand((5,5)) # notice square-matrix -> we can perform exp, otherwise do transpose

print(M)
print("-"*55)

print(M.mm(M))
print(M.matrix_power(2))

tensor([[0.1353, 0.9620, 0.1901, 0.9614, 0.3504],
        [0.7192, 0.6707, 0.4126, 0.6405, 0.2624],
        [0.2137, 0.3011, 0.6417, 0.6017, 0.3035],
        [0.9257, 0.9979, 0.8355, 0.4543, 0.1404],
        [0.9281, 0.4380, 0.6225, 0.9091, 0.5664]])
-------------------------------------------------------
tensor([[1.9659, 1.9455, 1.5660, 1.6159, 0.6909],
        [1.5042, 2.0199, 1.3767, 1.8987, 0.7917],
        [1.2213, 1.3341, 1.2683, 1.3337, 0.6050],
        [1.5723, 2.3261, 1.5908, 2.3658, 0.9830],
        [1.9408, 2.5293, 1.8688, 2.4752, 1.0774]])
tensor([[1.9659, 1.9455, 1.5660, 1.6159, 0.6909],
        [1.5042, 2.0199, 1.3767, 1.8987, 0.7917],
        [1.2213, 1.3341, 1.2683, 1.3337, 0.6050],
        [1.5723, 2.3261, 1.5908, 2.3658, 0.9830],
        [1.9408, 2.5293, 1.8688, 2.4752, 1.0774]])


### element-wise multiplication

In [45]:
print(x)
print(y)
z = x * y
print(z)

tensor([1, 2, 3])
tensor([9, 8, 7])
tensor([ 9, 16, 21])


### Batch Matrix multiplication

In [56]:
batch = 32
n = 10
m = 20
p = 30

tensor1 = torch.rand((batch,n,m))
print(tensor1.shape)

tensor2 = torch.rand((batch,m,p))
print(tensor2.shape)

out_bmm = torch.bmm(tensor1, tensor2) # batch mm
print(out_bmm.shape)

torch.Size([32, 10, 20])
torch.Size([32, 20, 30])
torch.Size([32, 10, 30])


### dot product

In [57]:
z = torch.dot(x, y)

### Broadcasting

In [81]:
x1 = torch.tensor([[1,2],[10,11]])
x2 = torch.tensor([5,6])
print(x1)
print(x2)
print('-'*30)

z1 = x1 + x2
z2 = x1 ** x2
z3 = x1 + x2.reshape(2,1)

print(z1)
print(z2)
print(z3)

tensor([[ 1,  2],
        [10, 11]])
tensor([5, 6])
------------------------------
tensor([[ 6,  8],
        [15, 17]])
tensor([[      1,      64],
        [ 100000, 1771561]])
tensor([[ 6,  7],
        [16, 17]])


### sum

In [87]:
print(x1)

tensor([[ 1,  2],
        [10, 11]])


In [98]:
sum_vert = torch.sum(x1, dim=0)
sum_horiz = torch.sum(x1, dim=1)
print(sum_vert)
print(sum_horiz)

tensor([11, 13])
tensor([ 3, 21])


### max, min

In [102]:
values, indices = torch.max(x1, dim=0)
print(values)
print(indices)

tensor([10, 11])
tensor([1, 1])


### abs

In [104]:
abs_x = torch.abs(x1)
print(abs_x)

tensor([[ 1,  2],
        [10, 11]])


### argmax/argmin

In [107]:
print(x1)
z = torch.argmax(x1, dim=0)
print(z)

tensor([[ 1,  2],
        [10, 11]])
tensor([1, 1])


### mean, std

In [116]:
x1 = x1.float()

In [118]:
# print(torch.mean(x1))
print(torch.std_mean(x1))
print(torch.mean(x1))
print(torch.std(x1))

(tensor(5.2281), tensor(6.))
tensor(6.)
tensor(5.2281)


### eq

In [121]:
x = torch.tensor([[1,2,3],[4,5,6]])
y = torch.tensor([[1,2,3],[7,8,9]])

z = torch.eq(x,y)
print(z)

tensor([[ True,  True,  True],
        [False, False, False]])


### sort

In [128]:
values, indices = torch.sort(y, dim=1, descending=True)
print(y)
print(values)
print(indices)

tensor([[1, 2, 3],
        [7, 8, 9]])
tensor([[3, 2, 1],
        [9, 8, 7]])
tensor([[2, 1, 0],
        [2, 1, 0]])


### clamp

In [131]:
print(x)
z = torch.clamp(x, min=3) # check all elements of x that are less than "min" and set to "min"
print(z)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[3, 3, 3],
        [4, 5, 6]])


### any / all

In [132]:
x = torch.tensor([1,0,1,1,1], dtype=torch.bool)

In [133]:
x

tensor([ True, False,  True,  True,  True])

In [134]:
z = torch.any(x)
print(z)

tensor(True)


In [137]:
z = torch.all(x)
print(z)

tensor(False)
